In [3]:
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow import keras
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras.utils import to_categorical


In [4]:
pip install tensorflow[and-cuda]

Note: you may need to restart the kernel to use updated packages.


In [5]:
# Load data
(x_train, y_train), (x_test, y_test) = keras.datasets.cifar10.load_data()

170498071/170498071 [==============================] - 4s 0us/step


In [6]:
# Normalize data
x_train = x_train / 255.0
x_test = x_test / 255.0

In [7]:
# Flatten images
nsamples, nx, ny, nrgb = x_train.shape
x_train_flat = x_train.reshape((nsamples, nx*ny*nrgb))
x_test_flat = x_test.reshape((x_test.shape[0], nx*ny*nrgb))

In [8]:
# Convert labels to one-hot encoding
y_train_cat = to_categorical(y_train, num_classes=10)
y_test_cat = to_categorical(y_test, num_classes=10)

In [9]:
# Build logistic regression model
model = Sequential([
    Dense(10, input_dim=nx*ny*nrgb, activation='softmax')
])

In [10]:
# Compile the model
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [11]:
# Train the model
model.fit(x_train_flat, y_train_cat, epochs=10, batch_size=32, validation_split=0.1)

Epoch 1/10
1407/1407 [==============================] - 2s 963us/step - loss: 1.9605 - accuracy: 0.3154 - val_loss: 2.0591 - val_accuracy: 0.2934
Epoch 2/10
1407/1407 [==============================] - 1s 847us/step - loss: 1.8882 - accuracy: 0.3497 - val_loss: 1.8911 - val_accuracy: 0.3486
Epoch 3/10
1407/1407 [==============================] - 1s 862us/step - loss: 1.8547 - accuracy: 0.3642 - val_loss: 1.8706 - val_accuracy: 0.3614
Epoch 4/10
1407/1407 [==============================] - 1s 854us/step - loss: 1.8439 - accuracy: 0.3701 - val_loss: 1.8882 - val_accuracy: 0.3446
Epoch 5/10
1407/1407 [==============================] - 1s 861us/step - loss: 1.8317 - accuracy: 0.3745 - val_loss: 1.9968 - val_accuracy: 0.3214
Epoch 6/10
1407/1407 [==============================] - 1s 857us/step - loss: 1.8251 - accuracy: 0.3772 - val_loss: 1.8296 - val_accuracy: 0.3830
Epoch 7/10
1407/1407 [==============================] - 1s 851us/step - loss: 1.8093 - accuracy: 0.3829 - val_loss: 1.9904 -

In [12]:
# Evaluate the model
loss, accuracy = model.evaluate(x_test_flat, y_test_cat)
print(f"Test accuracy: {accuracy:.3f}")

313/313 [==============================] - 0s 615us/step - loss: 2.0056 - accuracy: 0.3107
Test accuracy: 0.311


In [13]:
# Predictions for further evaluation
y_pred = model.predict(x_test_flat)
y_pred_classes = np.argmax(y_pred, axis=1)

print(classification_report(y_test, y_pred_classes))
print(confusion_matrix(y_test.ravel(), y_pred_classes))

313/313 [==============================] - 0s 537us/step
              precision    recall  f1-score   support

           0       0.65      0.18      0.28      1000
           1       0.55      0.30      0.39      1000
           2       0.37      0.02      0.04      1000
           3       0.32      0.10      0.16      1000
           4       0.22      0.69      0.33      1000
           5       0.31      0.32      0.32      1000
           6       0.63      0.11      0.19      1000
           7       0.61      0.16      0.25      1000
           8       0.46      0.43      0.45      1000
           9       0.24      0.79      0.37      1000

    accuracy                           0.31     10000
   macro avg       0.44      0.31      0.28     10000
weighted avg       0.44      0.31      0.28     10000

[[178  28   1   7 194  27   2   8 183 372]
 [  6 299   3  17  73  38   6  17  69 472]
 [ 32  31  23  21 556  85  18  10  47 177]
 [  3  29   8 105 324 223   9   9  40 250]
 [ 11  10   