In [1]:
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow import keras
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.callbacks import EarlyStopping

In [2]:
pip install tensorflow[and-cuda]

Note: you may need to restart the kernel to use updated packages.


In [13]:
# Load data
(x_train, y_train), (x_test, y_test) = keras.datasets.cifar10.load_data()
print (x_train)

[[[[ 59  62  63]
   [ 43  46  45]
   [ 50  48  43]
   ...
   [158 132 108]
   [152 125 102]
   [148 124 103]]

  [[ 16  20  20]
   [  0   0   0]
   [ 18   8   0]
   ...
   [123  88  55]
   [119  83  50]
   [122  87  57]]

  [[ 25  24  21]
   [ 16   7   0]
   [ 49  27   8]
   ...
   [118  84  50]
   [120  84  50]
   [109  73  42]]

  ...

  [[208 170  96]
   [201 153  34]
   [198 161  26]
   ...
   [160 133  70]
   [ 56  31   7]
   [ 53  34  20]]

  [[180 139  96]
   [173 123  42]
   [186 144  30]
   ...
   [184 148  94]
   [ 97  62  34]
   [ 83  53  34]]

  [[177 144 116]
   [168 129  94]
   [179 142  87]
   ...
   [216 184 140]
   [151 118  84]
   [123  92  72]]]


 [[[154 177 187]
   [126 137 136]
   [105 104  95]
   ...
   [ 91  95  71]
   [ 87  90  71]
   [ 79  81  70]]

  [[140 160 169]
   [145 153 154]
   [125 125 118]
   ...
   [ 96  99  78]
   [ 77  80  62]
   [ 71  73  61]]

  [[140 155 164]
   [139 146 149]
   [115 115 112]
   ...
   [ 79  82  64]
   [ 68  70  55]
   [ 67  69

In [4]:
# Normalize data
x_train = x_train / 255.0
x_test = x_test / 255.0

In [5]:
# Flatten images
nsamples, nx, ny, nrgb = x_train.shape
x_train_flat = x_train.reshape((nsamples, nx*ny*nrgb))
x_test_flat = x_test.reshape((x_test.shape[0], nx*ny*nrgb))

In [6]:
# Convert labels to one-hot encoding
y_train_cat = to_categorical(y_train, num_classes=10)
y_test_cat = to_categorical(y_test, num_classes=10)

In [7]:
# Build logistic regression model
model = Sequential([
    Dense(10, input_dim=nx*ny*nrgb, activation='softmax')
])

In [8]:
# Compile the model
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [9]:
# Train the model
early_stop = EarlyStopping(monitor='val_loss', patience=5)
model.fit(x_train_flat, y_train_cat, epochs=50, batch_size=32, validation_split=0.1, callbacks=[early_stop])

Epoch 1/50
1407/1407 [==============================] - 2s 1ms/step - loss: 1.9833 - accuracy: 0.3086 - val_loss: 1.9074 - val_accuracy: 0.3388
Epoch 2/50
1407/1407 [==============================] - 1s 902us/step - loss: 1.8826 - accuracy: 0.3511 - val_loss: 1.8127 - val_accuracy: 0.3806
Epoch 3/50
1407/1407 [==============================] - 1s 891us/step - loss: 1.8533 - accuracy: 0.3640 - val_loss: 1.8308 - val_accuracy: 0.3752
Epoch 4/50
1407/1407 [==============================] - 1s 946us/step - loss: 1.8470 - accuracy: 0.3674 - val_loss: 1.8141 - val_accuracy: 0.3842
Epoch 5/50
1407/1407 [==============================] - 1s 927us/step - loss: 1.8386 - accuracy: 0.3706 - val_loss: 1.9346 - val_accuracy: 0.3450
Epoch 6/50
1407/1407 [==============================] - 1s 906us/step - loss: 1.8249 - accuracy: 0.3751 - val_loss: 1.7852 - val_accuracy: 0.3782
Epoch 7/50
1407/1407 [==============================] - 1s 875us/step - loss: 1.8135 - accuracy: 0.3796 - val_loss: 1.8991 - v

In [10]:
# Evaluate the model
loss, accuracy = model.evaluate(x_test_flat, y_test_cat)
print(f"Test accuracy: {accuracy:.3f}")

313/313 [==============================] - 0s 627us/step - loss: 1.8808 - accuracy: 0.3414
Test accuracy: 0.341


In [11]:
# Predictions for further evaluation
y_pred = model.predict(x_test_flat)
y_pred_classes = np.argmax(y_pred, axis=1)

print(classification_report(y_test, y_pred_classes))
print(confusion_matrix(y_test.ravel(), y_pred_classes))

313/313 [==============================] - 0s 553us/step
              precision    recall  f1-score   support

           0       0.45      0.24      0.32      1000
           1       0.51      0.45      0.47      1000
           2       0.37      0.08      0.13      1000
           3       0.30      0.06      0.09      1000
           4       0.43      0.14      0.21      1000
           5       0.19      0.72      0.30      1000
           6       0.47      0.36      0.41      1000
           7       0.48      0.38      0.43      1000
           8       0.36      0.72      0.48      1000
           9       0.58      0.27      0.37      1000

    accuracy                           0.34     10000
   macro avg       0.41      0.34      0.32     10000
weighted avg       0.41      0.34      0.32     10000

[[245  34   6   5   4 231  16  46 397  16]
 [ 45 446   3  10   8 167  24  44 183  70]
 [ 45  28  81  15  51 495  92  61 124   8]
 [ 15  47  23  55  16 648  50  35  93  18]
 [ 30  14  4