In [1]:
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow import keras
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.callbacks import EarlyStopping

In [2]:
pip install tensorflow[and-cuda]

zsh:1: no matches found: tensorflow[and-cuda]
Note: you may need to restart the kernel to use updated packages.


In [3]:
# Load data
(x_train, y_train), (x_test, y_test) = keras.datasets.cifar10.load_data()
print (x_train)

[[[[ 59  62  63]
   [ 43  46  45]
   [ 50  48  43]
   ...
   [158 132 108]
   [152 125 102]
   [148 124 103]]

  [[ 16  20  20]
   [  0   0   0]
   [ 18   8   0]
   ...
   [123  88  55]
   [119  83  50]
   [122  87  57]]

  [[ 25  24  21]
   [ 16   7   0]
   [ 49  27   8]
   ...
   [118  84  50]
   [120  84  50]
   [109  73  42]]

  ...

  [[208 170  96]
   [201 153  34]
   [198 161  26]
   ...
   [160 133  70]
   [ 56  31   7]
   [ 53  34  20]]

  [[180 139  96]
   [173 123  42]
   [186 144  30]
   ...
   [184 148  94]
   [ 97  62  34]
   [ 83  53  34]]

  [[177 144 116]
   [168 129  94]
   [179 142  87]
   ...
   [216 184 140]
   [151 118  84]
   [123  92  72]]]


 [[[154 177 187]
   [126 137 136]
   [105 104  95]
   ...
   [ 91  95  71]
   [ 87  90  71]
   [ 79  81  70]]

  [[140 160 169]
   [145 153 154]
   [125 125 118]
   ...
   [ 96  99  78]
   [ 77  80  62]
   [ 71  73  61]]

  [[140 155 164]
   [139 146 149]
   [115 115 112]
   ...
   [ 79  82  64]
   [ 68  70  55]
   [ 67  69

In [4]:
# Normalize data
x_train = x_train / 255.0
x_test = x_test / 255.0

In [5]:
# Flatten images
nsamples, nx, ny, nrgb = x_train.shape
x_train_flat = x_train.reshape((nsamples, nx*ny*nrgb))
x_test_flat = x_test.reshape((x_test.shape[0], nx*ny*nrgb))

In [6]:
# Convert labels to one-hot encoding
y_train_cat = to_categorical(y_train, num_classes=10)
y_test_cat = to_categorical(y_test, num_classes=10)

In [7]:
# Build logistic regression model
model = Sequential([
    Dense(10, input_dim=nx*ny*nrgb, activation='softmax')
])

In [8]:
# Compile the model
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [9]:
# Train the model
early_stop = EarlyStopping(monitor='val_loss', patience=5)
model.fit(x_train_flat, y_train_cat, epochs=50, batch_size=32, validation_split=0.1, callbacks=[early_stop])

Epoch 1/50
   1/1407 [..............................] - ETA: 2:55 - loss: 2.5622 - accuracy: 0.0000e+00

2024-05-02 02:59:15.184650: W tensorflow/tsl/platform/profile_utils/cpu_utils.cc:128] Failed to get CPU frequency: 0 Hz


1407/1407 [==============================] - 1s 539us/step - loss: 1.9712 - accuracy: 0.3155 - val_loss: 1.9194 - val_accuracy: 0.3474
Epoch 2/50
1407/1407 [==============================] - 1s 425us/step - loss: 1.8790 - accuracy: 0.3508 - val_loss: 1.9560 - val_accuracy: 0.3036
Epoch 3/50
1407/1407 [==============================] - 1s 420us/step - loss: 1.8621 - accuracy: 0.3586 - val_loss: 1.9309 - val_accuracy: 0.3252
Epoch 4/50
1407/1407 [==============================] - 1s 441us/step - loss: 1.8512 - accuracy: 0.3661 - val_loss: 2.2154 - val_accuracy: 0.2846
Epoch 5/50
1407/1407 [==============================] - 1s 443us/step - loss: 1.8416 - accuracy: 0.3700 - val_loss: 1.8268 - val_accuracy: 0.3628
Epoch 6/50
1407/1407 [==============================] - 1s 440us/step - loss: 1.8177 - accuracy: 0.3787 - val_loss: 1.8516 - val_accuracy: 0.3678
Epoch 7/50
1407/1407 [==============================] - 1s 426us/step - loss: 1.8036 - accuracy: 0.3853 - val_loss: 1.8611 - val_accura

In [10]:
# Evaluate the model
loss, accuracy = model.evaluate(x_test_flat, y_test_cat)
print(f"Test accuracy: {accuracy:.3f}")

313/313 [==============================] - 0s 317us/step - loss: 1.8773 - accuracy: 0.3497
Test accuracy: 0.350


In [11]:
# Predictions for further evaluation
y_pred = model.predict(x_test_flat)
y_pred_classes = np.argmax(y_pred, axis=1)

print(classification_report(y_test, y_pred_classes))
print(confusion_matrix(y_test.ravel(), y_pred_classes))

313/313 [==============================] - 0s 239us/step
              precision    recall  f1-score   support

           0       0.54      0.24      0.33      1000
           1       0.52      0.42      0.46      1000
           2       0.28      0.31      0.29      1000
           3       0.19      0.67      0.29      1000
           4       0.53      0.07      0.13      1000
           5       0.39      0.21      0.27      1000
           6       0.46      0.31      0.37      1000
           7       0.48      0.40      0.43      1000
           8       0.43      0.61      0.50      1000
           9       0.56      0.26      0.36      1000

    accuracy                           0.35     10000
   macro avg       0.44      0.35      0.34     10000
weighted avg       0.44      0.35      0.34     10000

[[242  29  78 276   1   9  15  56 278  16]
 [ 23 416  37 209   7  30  19  50 123  86]
 [ 35  22 309 387   9  35  86  52  57   8]
 [  3  24  77 673   4  98  47  23  37  14]
 [ 27   7 23